providers = ["node", "python"]

[phases.setup]
nixPkgs = ["nodejs-20_x", "python311", "ffmpeg"]

[phases.install]
cmds = ["npm install", "pip install -r requirements.txt"]

[start]
cmd = "node server.js"
